### PR TITLE
Added AutoStart support

### PR DESCRIPTION
**Pull request by BrightCandle**
Addresses  issue #7 by adding Auto Start to default settings, popup and right click menu.

### CODE REVIEW

**Comment by nanocortex** [comment]
Hi, thanks for your contribution! I'm thinking that auto start should be enabled by default. What do you think?

**Comment by BrightCandle** [comment]
Certainly I think it's how the application should work. Metube seemed to
come with AutoStart Off by default so I went with their defaults so the
extension behaved the same way the web application now does, which is how
the other settings appear to be set in the code.

I can make arguments both ways, I certainly want it auto starting the
download myself. I am fine either way it's done and I can argue it both
ways.

**Comment by nanocortex** [comment]
MeTube seems to autostart by default in recent commit: https://github.com/alexta69/metube/commit/f0247415bf5ec6bfa6f08ad7a75aa1efbcd3a7b3, so please make it default to true, and I'll merge this PR.

**Comment by nanocortex** [comment]
@BrightCandle Hey, why you closed PR?

**Pull request closed without merging**
